// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            9
// Async Callback (empty):               1
// Total number of exported functions:  12

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    token_escrow
    (
        init => init
        upgrade => upgrade
        createOffer => create_offer
        cancelOffer => cancel_offer
        acceptOffer => accept_offer
        getOffer => get_offer
        getOffers => get_offers
        getOffersForUser => get_offers_for_user
        getCreatedOffers => get_created_offers
        getReceivedOffers => get_received_offers
        getLastOfferId => last_offer_id
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
